FROM mongo:latest
# Copia os ficheiros para dentro da imagem durante o build
COPY produtos.json /docker-entrypoint-initdb.d/
COPY categorias.json /docker-entrypoint-initdb.d/
COPY cores.json /docker-entrypoint-initdb.d/
COPY encomendas.json /docker-entrypoint-initdb.d/
COPY users.json /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/import.sh
RUN chmod +x /docker-entrypoint-initdb.d/import.sh